package zygarde.samples.todo

import io.kotest.matchers.collections.shouldContainExactlyInAnyOrder
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import zygarde.data.api.SortField
import zygarde.samples.todo.generated.dao.NoteDao
import zygarde.samples.todo.generated.dao.NoteScope
import zygarde.samples.todo.generated.dao.search
import zygarde.samples.todo.generated.dao.searchCount

/**
 * Runtime integration test for scoped DAO extension functions generated by @ScopeMarker/@NullEquivalent.
 * Covers edge cases that pure string-contains assertions cannot: empty collection, nullable skip,
 * sorted fallback, and NullEquivalent OR IS NULL semantics against a real JPA context.
 */
@DataJpaTest
@AutoConfigureTestDatabase
class NoteScopedQueryTest {
  @Autowired
  lateinit var noteDao: NoteDao

  @BeforeEach
  fun setUp() {
    noteDao.deleteAll()
    noteDao.saveAll(
      listOf(
        Note(title = "t1-public", tenantId = "t1", visibility = "PUBLIC"),
        Note(title = "t1-private", tenantId = "t1", visibility = "PRIVATE"),
        Note(title = "t1-null", tenantId = "t1", visibility = null),
        Note(title = "t2-public", tenantId = "t2", visibility = "PUBLIC"),
        Note(title = "t2-null", tenantId = "t2", visibility = null),
      )
    )
  }

  @Test
  fun `scope filters by tenantId`() {
    val results = noteDao.search(NoteScope(tenantId = "t1"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private", "t1-null")
  }

  @Test
  fun `nullable scope field left null should skip predicate`() {
    // visibility omitted — should not filter on it
    val results = noteDao.search(NoteScope(tenantId = "t2"))
    results shouldHaveSize 2
  }

  @Test
  fun `empty collection on a scope field is treated as no-filter`() {
    // Guardrail against a subtle gotcha: inList silently drops empty collections
    // (see ConditionActionImpl.inList), so an empty scope collection returns ALL
    // records for that field rather than zero. Callers expecting strict matching
    // must pre-check emptiness themselves.
    val results = noteDao.search(NoteScope(tenantId = emptyList()))
    results shouldHaveSize 5
  }

  @Test
  fun `NullEquivalent value includes records where the field is NULL`() {
    // visibility = "PUBLIC" is the @NullEquivalent sentinel → OR IS NULL branch
    val results = noteDao.search(NoteScope(tenantId = "t1", visibility = "PUBLIC"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-null")
  }

  @Test
  fun `non-NullEquivalent value should match only that value`() {
    val results = noteDao.search(NoteScope(tenantId = "t1", visibility = "PRIVATE"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-private")
  }

  @Test
  fun `sorted overload with sorts=null should return the same records as the default overload`() {
    // exercises the sorts?.let { ... } ?: search(scope, searchContent) fallback branch
    // — scope predicates must not be applied in a way that excludes matching rows.
    val sorted = noteDao.search(NoteScope(tenantId = "t1"), sorts = null, searchContent = {})
    sorted.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private", "t1-null")
  }

  @Test
  fun `sorted overload with sorts should order results`() {
    val sorted = noteDao.search(
      NoteScope(tenantId = "t1"),
      sorts = listOf(SortField(field = "title")),
      searchContent = {},
    )
    sorted.map { it.title } shouldBe listOf("t1-null", "t1-private", "t1-public")
  }

  @Test
  fun `searchCount respects scope predicates`() {
    noteDao.searchCount(NoteScope(tenantId = "t1")) shouldBe 3L
    noteDao.searchCount(NoteScope(tenantId = "t2", visibility = "PUBLIC")) shouldBe 2L
  }
}
