package zygarde.samples.todo

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.collections.shouldContainExactlyInAnyOrder
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import zygarde.core.exception.ApiErrorCode
import zygarde.core.exception.BusinessException
import zygarde.data.api.PagingAndSortingRequest
import zygarde.data.api.PagingRequest
import zygarde.data.api.SortField
import zygarde.data.jpa.search.ScopeFilter
import zygarde.samples.todo.generated.dao.NoteDao
import zygarde.samples.todo.generated.dao.NoteScope
import zygarde.samples.todo.generated.dao.ScopedTaskDao
import zygarde.samples.todo.generated.dao.ScopedTaskScope
import zygarde.samples.todo.generated.dao.search
import zygarde.samples.todo.generated.dao.searchCount
import zygarde.samples.todo.generated.dao.searchOne
import zygarde.samples.todo.generated.dao.searchOneOrThrow
import zygarde.samples.todo.generated.dao.searchPage
import zygarde.samples.todo.generated.search.id
import zygarde.samples.todo.generated.search.tenantId
import zygarde.samples.todo.generated.search.title
import zygarde.samples.todo.generated.search.visibility

/**
 * Runtime integration test for scoped DAO extension functions generated by @ScopeMarker/@NullEquivalent.
 * Covers edge cases that pure string-contains assertions cannot: empty collection, nullable skip,
 * sorted fallback, and NullEquivalent OR IS NULL semantics against a real JPA context.
 */
@DataJpaTest
@AutoConfigureTestDatabase
class NoteScopedQueryTest {
  @Autowired
  lateinit var noteDao: NoteDao

  @Autowired
  lateinit var scopedTaskDao: ScopedTaskDao

  @BeforeEach
  fun setUp() {
    noteDao.deleteAll()
    scopedTaskDao.deleteAll()
    noteDao.saveAll(
      listOf(
        Note(title = "t1-public", tenantId = "t1", visibility = "PUBLIC"),
        Note(title = "t1-private", tenantId = "t1", visibility = "PRIVATE"),
        Note(title = "t1-null", tenantId = "t1", visibility = null),
        Note(title = "t2-public", tenantId = "t2", visibility = "PUBLIC"),
        Note(title = "t2-null", tenantId = "t2", visibility = null),
      )
    )
    scopedTaskDao.saveAll(
      listOf(
        ScopedTask(name = "active", status = ScopedTaskStatus.ACTIVE, excludedCode = "ACTIVE-CODE", linkedId = 1),
        ScopedTask(name = "cancelled", status = ScopedTaskStatus.CANCELLED, excludedCode = "CANCELLED-CODE", deletedAt = "deleted"),
        ScopedTask(name = "archived", status = ScopedTaskStatus.ARCHIVED, excludedCode = "ARCHIVED-CODE", linkedId = 2),
        ScopedTask(name = "null-status", status = null, excludedCode = null, deletedAt = "deleted"),
      )
    )
  }

  @Test
  fun `scope filters by tenantId`() {
    val results = noteDao.search(NoteScope(tenantId = "t1"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private", "t1-null")
  }

  @Test
  fun `nullable scope field left null should skip predicate`() {
    // visibility omitted — should not filter on it
    val results = noteDao.search(NoteScope(tenantId = "t2"))
    results shouldHaveSize 2
  }

  @Test
  fun `empty collection on a scope field matches nothing`() {
    val results = noteDao.search(NoteScope(tenantId = emptyList()))
    results shouldHaveSize 0
  }

  @Test
  fun `ScopeFilter All explicitly skips a required scope predicate`() {
    val results = noteDao.search(NoteScope(tenantId = ScopeFilter.All))

    results shouldHaveSize 5
  }

  @Test
  fun `NullEquivalent value includes records where the field is NULL`() {
    // visibility = "PUBLIC" is the @NullEquivalent sentinel → OR IS NULL branch
    val results = noteDao.search(NoteScope(tenantId = "t1", visibility = "PUBLIC"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-null")
  }

  @Test
  fun `non-NullEquivalent value should match only that value`() {
    val results = noteDao.search(NoteScope(tenantId = "t1", visibility = "PRIVATE"))
    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-private")
  }

  @Test
  fun `sorted overload with sorts=null should return the same records as the default overload`() {
    // exercises the sorts?.let { ... } ?: search(scope, searchContent) fallback branch
    // — scope predicates must not be applied in a way that excludes matching rows.
    val sorted = noteDao.search(NoteScope(tenantId = "t1"), sorts = null, searchContent = {})
    sorted.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private", "t1-null")
  }

  @Test
  fun `sorted overload with sorts should order results`() {
    val sorted = noteDao.search(
      NoteScope(tenantId = "t1"),
      sorts = listOf(SortField(field = "title")),
      searchContent = {},
    )
    sorted.map { it.title } shouldBe listOf("t1-null", "t1-private", "t1-public")
  }

  @Test
  fun `searchCount respects scope predicates`() {
    noteDao.searchCount(NoteScope(tenantId = "t1")) shouldBe 3L
    noteDao.searchCount(NoteScope(tenantId = "t2", visibility = "PUBLIC")) shouldBe 2L
  }

  @Test
  fun `generated scope overloads support limit one page and throwing lookups`() {
    noteDao.search(NoteScope(tenantId = "t1"), searchContent = { title() startsWith "t1" }, limit = 2) shouldHaveSize 2
    noteDao.searchOne(NoteScope(tenantId = "t1")) { title() eq "t1-private" }!!.title shouldBe "t1-private"
    noteDao.searchOneOrThrow(NoteScope(tenantId = "t2"), ApiErrorCode.NOT_FOUND) { title() eq "t2-public" }.title shouldBe "t2-public"
    shouldThrow<BusinessException> {
      noteDao.searchOneOrThrow(NoteScope(tenantId = "t2"), ApiErrorCode.NOT_FOUND) { title() eq "missing" }
    }.code shouldBe ApiErrorCode.NOT_FOUND

    val page = noteDao.searchPage(
      NoteScope(tenantId = "t1"),
      PagingAndSortingRequest().also {
        it.paging = PagingRequest(page = 1, pageSize = 2)
        it.sorts = listOf(SortField(field = "title"))
      }
    ) {
      visibility().isNotNull()
    }
    page.content.map { it.title } shouldBe listOf("t1-private", "t1-public")
  }

  @Test
  fun `generated Note search extensions should work for root and nested condition actions`() {
    val results = noteDao.search(NoteScope(tenantId = "t1")) {
      tenantId() eq "t1"
      title() contains "t1"
      visibility() inList listOf("PUBLIC", "PRIVATE")
      id() gt 0L
    }

    results.map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private")
  }

  @Test
  fun `NOT_IN excludes enum values and preserves null when sentinel is not excluded`() {
    val results = scopedTaskDao.search(ScopedTaskScope(status = listOf(ScopedTaskStatus.CANCELLED)))

    results.map { it.name } shouldContainExactlyInAnyOrder listOf("active", "archived", "null-status")
  }

  @Test
  fun `NOT_IN with an empty scoped value set matches nothing`() {
    scopedTaskDao.search(ScopedTaskScope(status = emptyList())) shouldHaveSize 0
  }

  @Test
  fun `NOT_IN excludes null when NullEquivalent sentinel is excluded`() {
    val results = scopedTaskDao.search(ScopedTaskScope(status = listOf(ScopedTaskStatus.ARCHIVED)))

    results.map { it.name } shouldContainExactlyInAnyOrder listOf("active", "cancelled")
  }

  @Test
  fun `NOT_IN supports enum complement without omitting future enum values`() {
    val excluded = ScopedTaskStatus.entries - ScopedTaskStatus.ACTIVE
    val results = scopedTaskDao.search(ScopedTaskScope(status = excluded))

    results.map { it.name } shouldContainExactlyInAnyOrder listOf("active")
  }

  @Test
  fun `IS_NULL and IS_NOT_NULL apply only when enabled`() {
    scopedTaskDao.search(ScopedTaskScope(deletedAt = true))
      .map { it.name } shouldContainExactlyInAnyOrder listOf("active", "archived")
    scopedTaskDao.search(ScopedTaskScope(linkedId = true))
      .map { it.name } shouldContainExactlyInAnyOrder listOf("active", "archived")
    scopedTaskDao.search(ScopedTaskScope(deletedAt = false, linkedId = false)) shouldHaveSize 4
  }

  @Test
  fun `IN keeps matches when values cross the 500-value chunk boundary`() {
    val tenantIds = (0 until 500).map { "missing-$it" } + "t1"

    noteDao.search(NoteScope(tenantId = tenantIds))
      .map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-private", "t1-null")
  }

  @Test
  fun `IN finds NullEquivalent sentinel across the 500-value chunk boundary`() {
    val visibilities = (0 until 500).map { "missing-$it" } + "PUBLIC"

    noteDao.search(
      NoteScope(
        tenantId = ScopeFilter.Of(listOf("t1")),
        visibility = ScopeFilter.Of(visibilities),
      )
    )
      .map { it.title } shouldContainExactlyInAnyOrder listOf("t1-public", "t1-null")
  }

  @Test
  fun `NOT_IN combines chunks with AND and handles a sentinel in the final chunk`() {
    val excludedCodes = (0 until 500).map { "missing-$it" } + "ARCHIVED-CODE"

    scopedTaskDao.search(ScopedTaskScope(status = null, excludedCode = excludedCodes))
      .map { it.name } shouldContainExactlyInAnyOrder listOf("active", "cancelled")
  }
}
