type Query {
  todos(filter: TodoFilter): [Todo!]!
  todo(id: Int!): Todo
  todosByIds(ids: [Int!]!): [Todo!]!
}

type Mutation {
  createTodo(input: TodoInput!): Todo!
  updateTodo(id: Int!, input: TodoInput!): Todo!
  deleteTodo(id: Int!): Boolean!
}

type Todo {
  id: ID!
  description: String!
  file: File
}

type File {
  id: String!
  name: String!
}

type Author {
  id: ID!
  name: String!
}

type Book {
  id: ID!
  title: String!
  author: Author
}

input TodoInput {
  description: String!
}

input TodoFilter {
  idEq: Int
  idsIn: [Int!]
  descriptionContains: String
}
